# REST

## Login
POST http://localhost:8080/admin/login
Content-Type: application/json

{
    "email": "sarunyu-d@rmutp.ac.th",
    "password": "1Password",
    "rememberMe": true
}

### Login (User)
POST http://localhost:8080/api/auth/local
Content-Type: application/json

{
    "identifier": "",
    "password": "1Password"
}

### Signup
POST http://localhost:8080/api/auth/local/register
Content-Type: application/json

{
    "username": "sarunyu.d",
    "email": "sarunyu-d@rmutp.ac.th",
    "password": "Password"
}

### Forgot Password (Admin)
POST http://localhost:8080/admin/forgot-password
Content-Type: application/json

{
    "email": "sarunyu-d@rmutp.ac.th",
    "url": "http://localhost:8080/admin"
}

### Forgot Password (User)
POST http://localhost:8080/api/auth/forgot-password
Content-Type: application/json

{
    "email": "sarunyu-d@rmutp.ac.th"
}



### Profile
GET http://localhost:8080/admin/users/me
Content-Type: application/json
authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg3NDgzNjQ2LCJleHAiOjE3OTAwNzU2NDZ9.7LaHZVarV1cQMy8P3yHdrz5SoDHszQiDObDuFgbgCMA

{
    
}



