# REST

@baseUrl = {{$dotenv BASE_URL}}

@adminEmail = {{$dotenv ADMIN_EMAIL}}
@adminPassword = {{$dotenv ADMIN_PASSWORD}}
@adminNewPassword = {{$dotenv ADMIN_NEW_PASSWORD}}

@userName = {{$dotenv USER_NAME}}
@userEmail = {{$dotenv USER_EMAIL}}
@userPassword = {{$dotenv USER_PASSWORD}}
@userNewPassword = {{$dotenv USER_NEW_PASSWORD}}


## 1. Admin Section

### 1.1 Login (Admin)
# @name adminLogin
POST {{baseUrl}}/admin/login
Content-Type: application/json

{
    "email": "{{adminEmail}}",
    "password": "{{adminPassword}}"
}

###
@adminToken = {{adminLogin.response.body.data.token}}

### 1.2 Forgot Password (Admin)
POST {{baseUrl}}/admin/forgot-password
Content-Type: application/json

{
    "email": "{{adminEmail}}"
}

###
@adminResetToken = {{$dotenv ADMIN_RESET_TOKEN}}

### 1.3 Reset Password (Admin)
POST {{baseUrl}}/admin/reset-password
Content-Type: application/json

{
    "resetPasswordToken": "{{adminResetToken}}",
    "password": "{{adminNewPassword}}"
}

### 1.4 Profile (Admin)
GET {{baseUrl}}/admin/users/me
Authorization: Bearer {{adminToken}}

## 2. User Section

### 2.1 Signup (User)
POST {{baseUrl}}/api/auth/local/register
Content-Type: application/json

{
    "username": "{{userName}}",
    "email": "{{userEmail}}",
    "password": "{{userPassword}}"
}

### 2.2 Login (User)
# @name userLogin
POST {{baseUrl}}/api/auth/local
Content-Type: application/json

{
    "identifier": "{{userEmail}}",
    "password": "{{userPassword}}"
}

###
@userToken = {{userLogin.response.body.jwt}}

### 2.3 Forgot Password (User)
POST {{baseUrl}}/api/auth/forgot-password
Content-Type: application/json

{
    "email": "{{userEmail}}"
}

###
@userResetToken = {{$dotenv USER_RESET_TOKEN}}

### 2.4 Reset Password (User)
POST {{baseUrl}}/api/auth/reset-password
Content-Type: application/json

{
    "code": "{{userResetToken}}",
    "password": "{{userNewPassword}}",
    "passwordConfirmation": "{{userNewPassword}}"
}

### 2.5 Profile (User)
GET {{baseUrl}}/api/users/me
Authorization: Bearer {{userToken}}