services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - 127.0.0.1:54327:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: 69-s3-admin
    ports:
      - 127.0.0.1:8083:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_REPLACE_SERVERS_ON_STARTUP=True
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    configs:
      - source: pgadmin-servers
        target: /pgadmin4/servers.json
    depends_on:
      - db

  app:
    image: prawee/strapi
    container_name: my_app
    ports:
      - 127.0.0.1:8080:1337
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=${DATABASE_DB}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db

volumes:
  postgres_data:

configs:
  pgadmin-servers:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "dxp-s3-db",
            "Host": "db",
            "Port": 5432,
            "MaintenanceDB": "${DATABASE_DB}",
            "Username": "${DATABASE_USER}",
            "Password": "${DATABASE_PASSWORD}",
            "SSLMode": "prefer",
            "KeepAlive": true
          }
        }
      }