services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db-admin
    ports:
      - "54327:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=sarunyu.d
      - POSTGRES_DB=sarunyu.d
    volumes:
      - db_data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: 69-s3-pgadmin
    ports:
      - "8084:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=sarunyu-d@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - db

volumes:
  db_data:
